=== Dathard/Magento-2-debug/app/etc/schema/env.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="env">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="category" type="envCategoryDeclaration" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="uniqueCategory">
            <xs:selector xpath="category"/>
            <xs:field xpath="@name"/>
        </xs:unique>
    </xs:element>

    <xs:complexType name="envCategoryDeclaration">
        <xs:sequence>
            <xs:element name="arguments" type="argumentsDeclaration" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required" />
    </xs:complexType>

    <xs:complexType name="argumentsDeclaration">
        <xs:sequence>
            <xs:element name="argument" type="argumentDeclaration" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="type" type="xs:string" use="required" />
    </xs:complexType>

    <xs:complexType name="argumentDeclaration">
        <xs:attribute name="name" type="xs:string" use="required" />
        <xs:attribute name="value" type="xs:string" use="required" />
    </xs:complexType>
</xs:schema>

=== Dathard/Magento-2-debug/app/etc/env.xml
<?xml version="1.0"?>
<env xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema/env.xsd">
    <category name="db">
        <arguments type="connection">
            <argument name="host" value="localhost" />
            <argument name="dbname" value="localhost" />
            <argument name="username" value="localhost" />
            <argument name="password" value="localhost" />
            <argument name="table_prefix" value="" />
        </arguments>
        <arguments type="connection">
            <argument name="host" value="localhost" />
            <argument name="dbname" value="localhost" />
            <argument name="username" value="localhost" />
            <argument name="password" value="localhost" />
            <argument name="table_prefix" value="" />
        </arguments>
    </category>
</env>
