=== Dathard/Magento-2-debug/app/etc/schema/routes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="routes">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="route" type="routeDeclaration" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="uniqueRouteName">
            <xs:annotation>
                <xs:documentation>
                    Module name must be unique.
                </xs:documentation>
            </xs:annotation>
            <xs:selector xpath="route"/>
            <xs:field xpath="@pattern"/>
        </xs:unique>
    </xs:element>

    <xs:complexType name="routeDeclaration">
        <xs:sequence>
            <xs:element name="arguments" type="argumentsDeclaration" minOccurs="0" maxOccurs="unbounded">
                <xs:key name="argumentName">
                    <xs:selector xpath="argument"></xs:selector>
                    <xs:field xpath="@name"></xs:field>
                </xs:key>
            </xs:element>
            <xs:element name="dynamicArguments" type="dynamicArgumentsDeclaration" minOccurs="0" maxOccurs="unbounded">
                <xs:key name="dynamicArgumentsName">
                    <xs:selector xpath="argument"></xs:selector>
                    <xs:field xpath="@name"></xs:field>
                </xs:key>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="pattern" type="xs:string" use="required" />
        <xs:attribute name="controller" type="xs:string" use="required" />
    </xs:complexType>

    <xs:complexType name="argumentsDeclaration">
        <xs:sequence>
            <xs:element name="argument" type="argumentDeclaration" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="argumentDeclaration">
        <xs:attribute name="name" type="xs:string" use="required" />
        <xs:attribute name="type" type="valueType" use="required" />
        <xs:attribute name="value" type="xs:string" use="required" />
    </xs:complexType>

    <xs:complexType name="dynamicArgumentsDeclaration">
        <xs:sequence>
            <xs:element name="argument" type="dynamicArgumentDeclaration" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="dynamicArgumentDeclaration">
        <xs:attribute name="name" type="xs:string" use="required" />
        <xs:attribute name="value" type="xs:string" use="required" />
    </xs:complexType>

    <xs:simpleType name="valueType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="int"/>
            <xs:enumeration value="string"/>
            <xs:enumeration value="bool"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== Dathard/Magento-2-debug/app/etc/routes.xml
<?xml version="1.0"?>
<routes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema/routes.xsd">
    <route pattern="debug/magento-1"  controller="App\Controller\Debug\Magento2">
        <arguments>
            <argument name="magentoVersion" type="int" value="1" />
        </arguments>
    </route>
    <route pattern="debug/magento-2"  controller="App\Controller\Debug\Magento">
        <arguments>
            <argument name="magentoVersion" type="int" value="2" />
        </arguments>
    </route>

    <route pattern="category/([0-9]+)/page=([0-9]+)"  controller="App\Controller\Debug\Magento">
        <arguments>
            <argument name="magentoVersion" type="int" value="2" />
        </arguments>
        <dynamicArguments>
            <argument name="categoryId" value="$1" />
            <argument name="page" value="$2" />
        </dynamicArguments>
    </route>
</routes>
